// web-svelte/src/components/layout/AppShell.svelte
<script lang="ts">
  import { ui } from '@/lib/state/ui.svelte'
  import TopBar from './TopBar.svelte'
  import SideNav from './SideNav.svelte'
  import type { Snippet } from 'svelte'

  let { children }: { children: Snippet } = $props()

  function onKey(e: KeyboardEvent) {
    const meta = e.metaKey || e.ctrlKey
    if (meta && e.key.toLowerCase() === 'k') {
      e.preventDefault()
      ui.openCommand()
    }
    if (meta && e.key.toLowerCase() === 'b') {
      e.preventDefault()
      ui.toggleSidebar()
    }
  }
</script>

<svelte:window onkeydown={onKey} />

<div class="shell" class:collapsed={ui.sidebarCollapsed}>
  <TopBar />
  <div class="body">
    <SideNav />
    <main class="main">
      {@render children()}
    </main>
  </div>
</div>

<style>
  .shell {
    display: flex;
    flex-direction: column;
    height: 100%;
    min-height: 0;
  }
  .body {
    display: flex;
    flex: 1;
    min-height: 0;
  }
  .main {
    flex: 1;
    min-width: 0;
    min-height: 0;
    overflow: hidden;
    background: var(--bg);
    display: flex;
    flex-direction: column;
  }
</style>

// web/src/components/layout/AppShell.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue'
import { useUiStore } from '@/stores/ui'
import TopBar from './TopBar.vue'
import SideNav from './SideNav.vue'

const ui = useUiStore()

function onKey(e: KeyboardEvent) {
  const meta = e.metaKey || e.ctrlKey
  if (meta && e.key.toLowerCase() === 'k') {
    e.preventDefault()
    ui.openCommand()
  }
  if (meta && e.key.toLowerCase() === 'b') {
    e.preventDefault()
    ui.toggleSidebar()
  }
}

onMounted(() => window.addEventListener('keydown', onKey))
onUnmounted(() => window.removeEventListener('keydown', onKey))
</script>

<template>
  <div class="shell" :class="{ collapsed: ui.sidebarCollapsed }">
    <TopBar />
    <div class="body">
      <SideNav />
      <main class="main">
        <slot />
      </main>
    </div>
  </div>
</template>

<style scoped>
.shell {
  display: flex;
  flex-direction: column;
  height: 100%;
  min-height: 0;
}
.body {
  display: flex;
  flex: 1;
  min-height: 0;
}
.main {
  flex: 1;
  min-width: 0;
  min-height: 0;
  overflow: hidden;
  background: var(--bg);
}
</style>
